- name: my copy module usecase
- hosts: all
- tasks:
  - name: install apache 2
    apt:
      name: apache 2 
      state: latest 

  - name: start apache 2
    service:
      name: apache 2 
      state: restarted
      enabled: true


  - name: deployment
    copy:
      src: ./index.html
      dest: /var/www/html/index.html    
