- name: my copy module usecase
  hosts: all
  become: yes
  tasks:
    - name: install apache2
      apt:
        name: apache2
        state: latest
        update_cache: yes

    - name: start apache2
      service:
        name: apache2
        state: restarted
        enabled: true

    - name: deployment
      copy:
        src: ./index.html
        dest: /var/www/html/index.html
