# yum a d apt module
# conditions
# priviledger (root permission)


- name: Installation File
  hosts: all
  tasks:
    - name: install apache 2
      apt: 
       - name: apache 2
         state: latest
         update_cache: yes
      when: ansible_os_family == "Debian"   
   
    - name: install httpd
      apt: 
       - name: httpd
         state: present
         update_cache: yes
      when: ansible_os_family == "Redhat"   
