# yum and apt module
# conditions
# privileges (root permission)

- name: Test Apache and Nginx Installation
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Install apache2 on Debian-based systems
      apt:
        name: apache2
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install httpd on RedHat-based systems
      yum:
        name: httpd
        state: present
        update_cache: yes
      when: ansible_os_family == "RedHat"
    
    - name: Install nginx on Debian-based systems
      package:
        name: nginx
        state: present
      when: ansible_os_family == "Debian"

    - name: Install nginx on Debian-based systems
      systemd:
        name: nginx
        enabled: yes
      