- name: my first playbook
  hosts: all
  vars:
     movie: "money heist"
  tasks:
    - name: first task
      debug:
        msg: "my first {{movie}}"
    - name: second task
      debug:
        msg: "my second {{movie}}-2"
