- name: my first playbook
  hosts: all
  vars:
    movie: "money heist"
  var_files:
   path:./var.txt
  tasks:
    - name: first task
      debug:
        msg: "my first {{ movie }}"
    
    - name: second task
      debug:
        msg: "my second {{ movie }}-2"
    
    - name: third task
      vars:
        movie: "Jurrasic Park"
      debug:
        msg: "my third {{ movie }}"
