- name: my first playbook
  hosts: all
  vars:
    movie: "money heist"
  vars_files:
    - ./var.txt
  vars_prompt: 
    - name: movie
      prompt: enter the name of the movie
  tasks:
    - name: first task
      debug:
        msg: "my first {{ movie }}"
    
    - name: second task
      debug:
        msg: "my second {{ movie }}-2"
    
    - name: third task
      vars:
        movie: "Jurrasic Park"
      debug:
        msg: "my third {{ movie }}"
  
    - name: get hostname
      shell: hostname
      register: movie
    - name: print hostname
      debug: 
        msg: "this is hostname"